apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'git@github.com:fervbmx/wazuh-cloud-environments.git'
      revision: rollback-application-set-with-multiple-sources
      files:
      - path: regions/eu-central-1/**/*.yaml
      - path: regions/us-east-1/**/*.yaml
  template:
    metadata:
      name: '{{ .namespace }}'
    spec:
      project: environments
      destination:
        server: '{{ .server }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      sources:
      - repoURL: 'git@github.com:fervbmx/wazuh-cloud-templates-environment.git'
        targetRevision: '{{ .version }}'
        path: './'
        helm:
          valueFiles:
          - values.yaml
          values: |
            indexer: {{ .indexer }}