apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: 'git@github.com:fervbmx/wazuh-cloud-environments.git'
      revision: git-generator
      files:
      - path: regions/eu-central-1/**/*.yaml
      - path: regions/us-east-1/**/*.yaml
  template:
    metadata:
      name: '{{ .namespace }}'
    spec:
      project: environments
      destination:
        server: '{{ .server }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: 'git@github.com:fervbmx/wazuh-cloud-templates-environment.git'
        targetRevision: '{{ .version }}'
        path: './'
        helm:
          valueFiles:
          - values.yaml
          values: |
            indexer: 
              environments:
                cluster_name: {{ .indexer.environments.cluster_name }}
