apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: 'env-ba2t3d3am2k2'
        region: 'us-east-1'
        server: 'https://kubernetes.default.svc'
        version: '4.3.11'
      - name: 'env-ca35599bb1b8'
        region: 'us-east-1'
        server: 'https://kubernetes.default.svc'
        version: '4.3.11'
      - name: 'env-pa2c323am2k2'
        region: 'eu-central-1'
        server: 'https://kubernetes.default.svc'
        version: '4.3.11'
  template:
    metadata:
      name: '{{ name }}'
    spec:
      project: environments
      destination:
        server: '{{ server }}'
        namespace: '{{ name }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      sources:
      - repoURL: 'git@github.com:fervbmx/wazuh-cloud-templates-environment.git'
        targetRevision: '{{ version }}'
        path: './'
        helm:
          valueFiles:
          - values.yaml
          - $values/regions/{{ region }}/{{ name }}/values.yaml
      - repoURL: 'git@github.com:fervbmx/wazuh-cloud-environments.git'
        targetRevision: HEAD
        path: 'regions/{{ region }}/{{ name }}'
        ref: values
  syncPolicy:
    preserveResourcesOnDeletion: true