apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: management
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 5.1.2
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.8.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          - name: velero-plugin-for-digitalocean
            image: digitalocean/velero-plugin:v1.1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        configuration:
          backupStorageLocation:
            - name: digital-ocean
              provider: velero.io/aws
              bucket: velero-k8-backups
              default: true
              config:
                region: sfo3
                s3Url: https://sfo3.digitaloceanspaces.com
          volumeSnapshotLocation:
            - name: digital-ocean
              provider: digitalocean.com/velero
              config:
                region: sfo3
        credentials:
          existingSecret: digital-ocean-credentials
          extraEnvVars:
            DIGITALOCEAN_TOKEN: digital-ocean-token
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero